[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_APP_URL = "https://quimicamax.netlify.app"

[context.deploy-preview.environment]
  NEXT_PUBLIC_APP_URL = "DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  NEXT_PUBLIC_APP_URL = "DEPLOY_PRIME_URL"
